#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 橄榄树

# Short bio or description (displayed in the header)
description: 不要问我从哪里来 我的故乡在远方

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/timg.jpeg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: tao0211@vip.qq.com
  facebook:
  flickr:
  github: ganlanshu0211/ganlanshu0211.github.io
  instagram:
  linkedin:
  pinterest:
  rss: RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://olive.ren

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

comments:
  gitalk: true
  gitalk_clientID: '38d7e60a1f455c62b6f4'
  gitalk_Secret: 'b7224449dedac4a6be267533ffba2e6419502119'
  gitalk_repo: 'ganlanshu0211.github.io'
  gitalk_owner: 'ganlanshu0211'
  gitalk_admin: 'ganlanshu0211'
  distractionFreeMode: true

paginate: 10
paginate_path: "/page:num/"